-- Seed data for Kolkata Tour AI
-- Generated based on backend/data/kolkata_places.json

USE kolkata_ai;

-- Clear existing data to avoid duplicates
-- Delete child records first to avoid foreign key constraint issues
DELETE FROM place_images;
DELETE FROM places;

INSERT INTO places (id, name, category, subcategory, description, history, nearby_recommendations, personal_tips, lat, lng, opening_hours, price, best_time, past_events, sentiment_tags, image_urls, source_url) VALUES
(1, 'Victoria Memorial', 'Landmark', 'Museum', 'A grand marble building dedicated to Queen Victoria, surrounded by sprawling gardens.', 'Built between 1906–1921 to commemorate Queen Victoria''s 25-year reign in India. Designed by William Emerson in Indo-Saracenic revivalist style.', '["Birla Planetarium", "St. Paul''s Cathedral", "Maidan tea stalls"]', 'The best time for photos is just before sunset when the white marble glows gold. Don''t miss the light and sound show in the evening.', 22.5448, 88.3426, 'Museum: 10:00–17:00 (Mon closed); Gardens: 05:30–18:15', 'Museum: ₹30 (Indians), ₹500 (Foreigners); Garden: ₹20', 'October to March, late afternoon', 'Hosted the G20 cultural dinner in 2023.', '["heritage", "photography", "peaceful", "romantic", "iconic"]', '["https://upload.wikimedia.org/wikipedia/commons/7/72/Victoria_Memorial_Kolkata_India.jpg"]', 'https://en.wikipedia.org/wiki/Victoria_Memorial,_Kolkata'),
(2, 'Howrah Bridge', 'Landmark', 'Bridge', 'An iconic cantilever bridge spanning the Hooghly River, a symbol of Kolkata.', 'Commissioned in 1943, it was the third-longest cantilever bridge at the time. It has no nuts and bolts; it''s held together by rivets.', '["Mullick Ghat Flower Market", "Prinsep Ghat"]', 'Walk across it early morning to see the city wake up. Avoid peak hours if you dislike crowds.', 22.5851, 88.3468, 'Open 24 hours', 'Free', 'Dawn or Dusk', 'Featured in films like ''Lion'' and ''Yuva''.', '["iconic", "busy", "river-view", "chaos", "engineering"]', '["https://upload.wikimedia.org/wikipedia/commons/d/d0/Howrah_Bridge_2020.jpg"]', 'https://en.wikipedia.org/wiki/Howrah_Bridge'),
(3, 'Indian Museum', 'Museum', 'History', 'The oldest and largest museum in India, housing rare antiques, armor, and fossils.', 'Founded in 1814 by the Asiatic Society of Bengal. It has a rare collection of Egyptian mummies.', '["Park Street", "New Market"]', 'It''s huge! Focus on the Archaeology and Art sections if you are short on time. The Egyptian mummy is a must-see.', 22.5579, 88.3511, '10:00–17:00 (Mon closed)', '₹75 (Indians), ₹500 (Foreigners)', 'Afternoon (good for escaping heat)', 'Bicentenary celebrations in 2014.', '["educational", "historical", "family", "ancient", "indoor"]', '["https://upload.wikimedia.org/wikipedia/commons/6/6a/Indian_Museum_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Indian_Museum,_Kolkata'),
(4, 'College Street Coffee House', 'Food & Drink', 'Cafe', 'A historic cafe that has been the hub of Kolkata''s intelligentsia for decades.', 'Originally Albert Hall, founded in 1876. It became the meeting place for poets, artists, and revolutionaries like Satyajit Ray and Amartya Sen.', '["College Street Book Market", "Presidency University"]', 'Don''t expect quick service or luxury. Go for the ''adda'' (chat) and nostalgia. Try the Cold Coffee and Mutton Afgani.', 22.5759, 88.3643, '09:00–21:00', '₹200 for two', 'Evening for the buzz', 'Countless literary debates and book launches.', '["nostalgic", "intellectual", "crowded", "cheap", "cultural"]', '["https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Coffee_House_Kolkata.jpg/1200px-Coffee_House_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Indian_Coffee_House'),
(5, 'Kumartuli', 'Cultural', 'Artisan District', 'A traditional potters'' quarter where clay idols of gods and goddesses are made.', 'The settlement dates back to the British era. It is famous for sculpting idols for Durga Puja.', '["Bagbazar Ghat", "Sovabazar Rajbari"]', 'Visit a month before Durga Puja (September) to see the idols being painted. Ask permission before taking close-up photos of artisans.', 22.5968, 88.3654, 'Best visited 10:00–17:00', 'Free', 'August-September', 'Durga Puja preparation frenzy.', '["artistic", "cultural", "unique", "photography", "narrow-lanes"]', '["https://upload.wikimedia.org/wikipedia/commons/3/3e/Kumartuli_Idol_Making.jpg"]', 'https://en.wikipedia.org/wiki/Kumartuli'),
(6, 'Prinsep Ghat', 'Landmark', 'Riverside', 'A beautiful Palladian porch on the banks of the Hooghly River.', 'Built in 1841 in memory of James Prinsep, a scholar who deciphered the Brahmi script.', '["Outram Ghat", "Scoop (Ice cream parlor)"]', 'Take a private boat ride on the river at sunset. It''s very romantic and offers great views of the Vidyasagar Setu.', 22.5505, 88.3348, 'Open 24 hours', 'Free (Boat rides chargeable)', 'Sunset', 'Cultural festivals and shoots.', '["romantic", "scenic", "sunset", "peaceful", "river"]', '["https://upload.wikimedia.org/wikipedia/commons/9/98/Prinsep_Ghat_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Prinsep_Ghat'),
(7, 'Dakshineswar Kali Temple', 'Temple', 'Pilgrimage', 'A famous Hindu navaratna temple located on the eastern bank of the Hooghly River.', 'Built in 1855 by Rani Rashmoni. The mystic Ramakrishna Paramahansa served as its priest.', '["Belur Math (via boat)", "Skywalk"]', 'The queue can be very long. Tuesdays and Saturdays are busiest. Use the Skywalk for easy access from the station.', 22.6544, 88.3571, '06:00–12:30, 15:00–20:30', 'Free', 'Early morning', 'Kali Puja', '["spiritual", "devotional", "crowded", "heritage"]', '["https://upload.wikimedia.org/wikipedia/commons/6/68/Dakshineswar_Kali_Temple_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Dakshineswar_Kali_Temple'),
(8, 'Park Street', 'Area', 'Food & Nightlife', 'The street that never sleeps, famous for its restaurants, pubs, and colonial charm.', 'Was the center of Kolkata''s nightlife in the swinging 60s. Home to iconic eateries like Flurys and Moulin Rouge.', '["Oxford Bookstore", "South Park Street Cemetery"]', 'Visit during Christmas! The lighting is spectacular. Try the Chelo Kebab at Peter Cat.', 22.5492, 88.3494, 'All day', 'Variable', 'December evenings', 'Christmas Carnival', '["vibrant", "nightlife", "foodie", "festive", "posh"]', '["https://upload.wikimedia.org/wikipedia/commons/c/c6/Park_Street_Kolkata_Christmas.jpg"]', 'https://en.wikipedia.org/wiki/Park_Street,_Kolkata'),
(9, 'Marble Palace', 'Heritage', 'Mansion', 'A palatial nineteenth-century mansion in North Kolkata, famous for its marble walls and floors.', 'Built in 1835 by Raja Rajendra Mullick. It houses a private zoo and a collection of Western art.', '["Jorasanko Thakur Bari"]', 'You need a permit from the West Bengal Tourism Information Bureau 24 hours in advance. Photography is strictly prohibited.', 22.5825, 88.3597, '10:00–16:00 (Mon, Thu closed)', 'Free (Permit required)', 'Morning', 'Private family events.', '["grand", "art", "hidden-gem", "strict", "quiet"]', '["https://upload.wikimedia.org/wikipedia/commons/8/86/Marble_Palace_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Marble_Palace_(Kolkata)'),
(10, 'South Park Street Cemetery', 'Heritage', 'Cemetery', 'An 18th-century non-church cemetery with massive gothic tombs.', 'Opened in 1767, it is one of the earliest non-church cemeteries in the world. It houses the grave of Henry Louis Vivian Derozio.', '["Park Street"]', 'It''s surprisingly peaceful. Great for history buffs and photographers. Can be a bit spooky!', 22.5440, 88.3508, '10:00–17:00', '₹20', 'Winter afternoon', 'Heritage walks', '["eerie", "peaceful", "historical", "gothic", "green"]', '["https://upload.wikimedia.org/wikipedia/commons/5/5e/South_Park_Street_Cemetery.jpg"]', 'https://en.wikipedia.org/wiki/South_Park_Street_Cemetery'),
(11, 'Eco Park', 'Park', 'Recreation', 'The biggest urban park in India, featuring themed areas like the Seven Wonders of the World.', 'Inaugurated in 2012 in New Town to promote eco-tourism.', '["Mother''s Wax Museum"]', 'It''s massive. Rent a cycle or take the toy train. The Japanese Garden is very serene.', 22.6037, 88.4656, '14:30–20:30 (Mon closed)', '₹30', 'Winter evenings', 'Concerts and Food Festivals', '["modern", "family", "nature", "huge", "fun"]', '["https://upload.wikimedia.org/wikipedia/commons/7/7a/Eco_Park_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Eco_Park,_New_Town'),
(12, 'Kalighat Kali Temple', 'Temple', 'Religious', 'One of the 51 Shakti Peethas, dedicated to the goddess Kali.', 'The current temple was built in 1809, but the site has been sacred for centuries. The name ''Calcutta'' is said to be derived from Kalighat.', '["Keoratala Burning Ghat"]', 'Beware of aggressive pandas (priests). Keep your belongings safe. The morning aarti is powerful.', 22.5186, 88.3420, '05:00–14:00, 17:00–22:30', 'Free', 'Early morning', 'Daily worship', '["intense", "devotional", "crowded", "ancient"]', '["https://upload.wikimedia.org/wikipedia/commons/f/f6/Kalighat_Kali_Temple.jpg"]', 'https://en.wikipedia.org/wiki/Kalighat_Kali_Temple'),
(13, 'Belur Math', 'Temple', 'Spiritual', 'The headquarters of the Ramakrishna Math and Mission.', 'Founded by Swami Vivekananda in 1897. The architecture fuses Hindu, Christian, and Islamic motifs to symbolize unity of religions.', '["Dakshineswar Temple"]', 'Sit by the river bank in the evening. It is incredibly peaceful. Silence is strictly maintained.', 22.6326, 88.3560, '06:00–11:30, 16:00–21:00', 'Free', 'Evening Aarti', 'Durga Puja (Kumari Puja is famous)', '["peaceful", "spiritual", "clean", "river-view", "meditative"]', '["https://upload.wikimedia.org/wikipedia/commons/1/16/Belur_Math_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Belur_Math'),
(14, 'New Market', 'Market', 'Shopping', 'A historic shopping destination that sells everything from clothes to cheese.', 'Opened in 1874 as Sir Stuart Hogg Market. It was the first municipal market in Kolkata.', '["Nizam''s (Kathi Rolls)"]', 'Bargain hard! Visit Nahoum''s Bakery for their rich fruit cake. It''s a maze, so try not to get lost.', 22.5586, 88.3524, '10:00–20:00 (Sun closed)', 'Variable', 'Weekdays', 'Christmas shopping rush', '["chaotic", "shopping", "historical", "foodie", "bustling"]', '["https://upload.wikimedia.org/wikipedia/commons/8/8f/New_Market_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/New_Market,_Kolkata'),
(15, 'Jorasanko Thakur Bari', 'Heritage', 'Museum', 'The ancestral home of the Tagore family.', 'Birthplace of Nobel laureate Rabindranath Tagore. It is now a museum dedicated to his life and works.', '["Marble Palace", "Girish Park"]', 'A must for literature lovers. The light and sound show is decent.', 22.5850, 88.3594, '10:30–17:00 (Mon closed)', '₹20 (Indians), ₹150 (Foreigners)', 'Afternoon', 'Rabindra Jayanti', '["literary", "cultural", "heritage", "quiet", "inspiring"]', '["https://upload.wikimedia.org/wikipedia/commons/e/e6/Jorasanko_Thakur_Bari.jpg"]', 'https://en.wikipedia.org/wiki/Jorasanko_Thakur_Bari'),
(16, 'Science City', 'Museum', 'Science Center', 'The largest science center in the Indian subcontinent, featuring interactive exhibits and a space theatre.', 'Inaugurated in 1997, it was developed by the National Council of Science Museums to popularize science.', '["Milan Mela Ground", "JW Marriott"]', 'Great for kids. The Time Machine ride and the 3D show are popular. Plan for at least 3-4 hours.', 22.5392, 88.3963, '10:00–19:00', '₹70 (Entry) + Rides extra', 'Morning to afternoon', 'Science fairs and exhibitions', '["educational", "family", "fun", "interactive", "modern"]', '["https://upload.wikimedia.org/wikipedia/commons/a/a6/Science_City_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Science_City,_Kolkata'),
(17, 'Nicco Park', 'Park', 'Amusement Park', 'An amusement park often called the ''Disneyland of West Bengal''.', 'Opened in 1991, it was the first amusement park in India to achieve ISO 9001 certification.', '["Nalban Boating Complex", "Salt Lake Stadium"]', 'Buy the package ticket that includes all rides to save money. The water park ''Wet-O-Wild'' is great in summer.', 22.5714, 88.4217, '10:30–19:30', '₹300 (Entry) to ₹1000 (Package)', 'Winter days', 'Musical nights', '["fun", "thrilling", "family", "crowded", "energetic"]', '["https://upload.wikimedia.org/wikipedia/commons/e/e3/Nicco_Park_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Nicco_Park'),
(18, 'Alipore Zoo', 'Park', 'Zoo', 'India''s oldest zoological park, home to a wide variety of animals including the Royal Bengal Tiger.', 'Opened in 1876 by Edward VII. It was home to Adwaita, a giant tortoise that lived for over 250 years.', '["National Library", "Taj Bengal"]', 'Visit in winter to see the migratory birds. It gets very crowded on holidays.', 22.5356, 88.3326, '09:00–17:00 (Thu closed)', '₹50', 'Winter mornings', 'Wildlife awareness camps', '["nature", "wildlife", "family", "crowded", "historic"]', '["https://upload.wikimedia.org/wikipedia/commons/f/f9/Alipore_Zoological_Gardens_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Alipore_Zoological_Gardens'),
(19, 'Eden Gardens', 'Landmark', 'Stadium', 'One of the most iconic cricket stadiums in the world, known as the ''Mecca of Indian Cricket''.', 'Established in 1864. It is the oldest and second-largest cricket stadium in India.', '["Maidan", "Babughat"]', 'Watching a match here is an electric experience. On non-match days, you might need permission to enter the stands.', 22.5646, 88.3433, '10:00–17:00 (Non-match days)', 'Varies by match', 'During a cricket match', '1987 World Cup Final, 2016 T20 World Cup Final', '["passionate", "sporty", "massive", "iconic", "loud"]', '["https://upload.wikimedia.org/wikipedia/commons/3/3u/Eden_Gardens_under_floodlights.jpg"]', 'https://en.wikipedia.org/wiki/Eden_Gardens'),
(20, 'St. Paul''s Cathedral', 'Religious', 'Church', 'A magnificent Anglican cathedral known for its Indo-Gothic architecture.', 'Completed in 1847, it was the first Episcopal Church in Asia. The original steeple fell in an earthquake in 1934 and was rebuilt.', '["Birla Planetarium", "Academy of Fine Arts"]', 'It is very quiet and peaceful inside. The stained glass windows are beautiful. Midnight Mass on Christmas Eve is special.', 22.5444, 88.3463, '09:00–18:00', 'Free', 'Christmas season', 'Christmas Midnight Mass', '["peaceful", "gothic", "spiritual", "beautiful", "grand"]', '["https://upload.wikimedia.org/wikipedia/commons/c/c3/St._Paul%27s_Cathedral_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/St._Paul%27s_Cathedral,_Kolkata'),
(21, 'Nakhoda Masjid', 'Religious', 'Mosque', 'The largest mosque in Kolkata, capable of accommodating 10,000 devotees.', 'Built in 1926 by Abdar Rahim Osman, a shipping magnate. Its architecture is influenced by Akbar''s tomb in Sikandra.', '["Royal Indian Hotel", "Burrabazar"]', 'Visit during Eid to see it lit up. The area around it serves amazing Mughlai food.', 22.5754, 88.3544, '06:00–20:00', 'Free', 'Eid festivals', 'Eid prayers', '["grand", "spiritual", "architectural", "busy", "historic"]', '["https://upload.wikimedia.org/wikipedia/commons/0/08/Nakhoda_Masjid_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Nakhoda_Masjid'),
(22, 'Botanical Gardens', 'Park', 'Nature', 'A massive garden famous for the Great Banyan Tree, which is over 250 years old.', 'Founded in 1787 by Colonel Robert Kyd. It was originally known as the Company Bagh.', '["Shalimar Ghat"]', 'It is located in Shibpur (Howrah), across the river. The Great Banyan Tree looks like a forest by itself. Wear comfortable walking shoes.', 22.5544, 88.2904, '08:00–17:00 (Mon closed)', '₹10 (Indians), ₹100 (Foreigners)', 'Winter mornings', 'Flower shows', '["green", "vast", "nature", "peaceful", "scientific"]', '["https://upload.wikimedia.org/wikipedia/commons/f/f2/The_Great_Banyan_Tree.jpg"]', 'https://en.wikipedia.org/wiki/Acharya_Jagadish_Chandra_Bose_Indian_Botanic_Garden'),
(23, 'Mother House', 'Religious', 'Pilgrimage', 'The headquarters of the Missionaries of Charity and the tomb of Mother Teresa.', 'Established by Mother Teresa in 1950. It serves as a place of pilgrimage for people from all over the world.', '["Ripon Street"]', 'The museum is small but very moving. It is a place of absolute silence and reflection.', 22.5533, 88.3636, '08:00–12:00, 15:00–18:00 (Thu closed)', 'Free', 'Morning', 'Mother Teresa''s canonization celebrations', '["humble", "spiritual", "peaceful", "inspiring", "quiet"]', '["https://upload.wikimedia.org/wikipedia/commons/0/0f/Mother_House_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Missionaries_of_Charity'),
(24, 'Birla Planetarium', 'Museum', 'Science', 'The largest planetarium in Asia and the second largest in the world.', 'Inaugurated in 1963 by Jawaharlal Nehru. Its architecture is modeled on the Buddhist Stupa at Sanchi.', '["St. Paul''s Cathedral", "Victoria Memorial"]', 'Check the show timings and language (English/Hindi/Bengali) before you go. The cosmic collision show is good.', 22.5453, 88.3476, '12:00–18:30', '₹100', 'Afternoon', 'Astronomy workshops', '["educational", "scientific", "family", "cool", "dark"]', '["https://upload.wikimedia.org/wikipedia/commons/3/3a/Birla_Planetarium_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Birla_Planetarium,_Kolkata'),
(25, 'Millennium Park', 'Park', 'Riverside', 'A private park along the Hooghly River, offering great views of the Howrah Bridge.', 'Opened in 1999 as part of the Kolkata Riverside Beautification Project.', '["Fairlie Ghat", "Shipping Corporation of India"]', 'Good for a casual evening stroll. The food court offers decent snacks. The view of the lit-up Howrah Bridge is excellent.', 22.5726, 88.3471, '10:00–20:00', '₹10', 'Evening', 'Musical fountain shows', '["riverside", "relaxing", "view", "family", "breezy"]', '["https://upload.wikimedia.org/wikipedia/commons/6/62/Millennium_Park_Kolkata.jpg"]', 'https://en.wikipedia.org/wiki/Millennium_Park,_Kolkata')
];
